[package]
name = "day14"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.93"
image = "0.25.5"

[[bin]]
name = "part1"
path = "src/bin/part1.rs"

[[bin]]
name = "part2"
path = "src/bin/part2.rs"
