[package]
name = "day15"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.93"
enum-iterator = "2.1.0"

[[bin]]
name = "part1"
path = "src/bin/part1.rs"

[[bin]]
name = "part2"
path = "src/bin/part2.rs"
