[package]
name = "day12"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.93"
itertools = "0.13.0"
lazy_static = "1.5.0"

[[bin]]
name = "part1"
path = "src/bin/part1.rs"

[[bin]]
name = "part2"
path = "src/bin/part2.rs"
